CREATE TABLE "public"."organization_members" (
  "id" bigint NOT NULL,
  "created_at" timestamp WITH time zone DEFAULT "now"() NOT NULL,
  "member_id" "uuid" NOT NULL,
  "member_role" "public"."organization_member_role" NOT NULL,
  "organization_id" "uuid" NOT NULL
);
ALTER TABLE "public"."organization_members" OWNER TO "postgres";
--
-- Name: organizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."organizations" (
  "created_at" timestamp WITH time zone DEFAULT "now"() NOT NULL,
  "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
  "title" character varying DEFAULT 'Test Organization'::character varying NOT NULL,
  "created_by" "uuid" NOT NULL
);
ALTER TABLE "public"."organizations" OWNER TO "postgres";
--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."user_profiles" (
  "id" "uuid" NOT NULL,
  "full_name" character varying,
  "avatar_url" character varying,
  "created_at" timestamp WITH time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."user_profiles" OWNER TO "postgres";
CREATE TABLE "public"."app_settings" (
  "id" bigint NOT NULL,
  "maintenance_status" "public"."maintenance_status" DEFAULT 'inactive'::"public"."maintenance_status",
  "scheduled_maintenance_ends_at" timestamp WITH time zone,
  "maintenance_message" "text"
);
-- ALTER TABLE "public"."app_settings" OWNER TO "supabase_admin";
--
-- Name: app_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE "public"."app_settings"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_settings_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."customers" (
  "stripe_customer_id" character varying NOT NULL,
  "organization_id" "uuid" NOT NULL
);
ALTER TABLE "public"."customers" OWNER TO "postgres";
--
-- Name: organization_join_invitations; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE "public"."organization_join_invitations" (
  "created_at" timestamp WITH time zone DEFAULT "now"() NOT NULL,
  "inviter_user_id" "uuid" NOT NULL,
  "status" "public"."organization_join_invitation_link_status" DEFAULT 'active'::"public"."organization_join_invitation_link_status" NOT NULL,
  "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
  "invitee_user_email" character varying NOT NULL,
  "organization_id" "uuid" NOT NULL,
  "invitee_organization_role" "public"."organization_member_role" NOT NULL DEFAULT 'member'::organization_member_role,
  "invitee_user_id" "uuid"
);
-- ALTER TABLE "public"."organization_join_invitations" OWNER TO "supabase_admin";
--
-- Name: organizations_private_info; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE "public"."organizations_private_info" (
  "id" "uuid" NOT NULL,
  "billing_address" "json",
  "payment_method" "json"
);
-- ALTER TABLE "public"."organizations_private_info" OWNER TO "supabase_admin";
--
-- Name: prices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."prices" (
  "id" character varying NOT NULL,
  "product_id" character varying,
  "active" boolean,
  "description" character varying,
  "unit_amount" bigint,
  "currency" character varying,
  "type" "public"."pricing_type",
  "interval" "public"."pricing_plan_interval",
  "interval_count" bigint,
  "trial_period_days" bigint,
  "metadata" "jsonb"
);
ALTER TABLE "public"."prices" OWNER TO "postgres";
--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."products" (
  "id" character varying NOT NULL,
  "active" boolean,
  "name" character varying,
  "description" character varying,
  "image" character varying,
  "metadata" "jsonb"
);
ALTER TABLE "public"."products" OWNER TO "postgres";
--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."subscriptions" (
  "id" character varying NOT NULL,
  "status" "public"."subscription_status",
  "metadata" "json",
  "price_id" character varying,
  "quantity" bigint,
  "cancel_at_period_end" boolean,
  "created" timestamp WITH time zone NOT NULL,
  "current_period_start" timestamp WITH time zone NOT NULL,
  "current_period_end" timestamp WITH time zone NOT NULL,
  "ended_at" timestamp WITH time zone,
  "cancel_at" timestamp WITH time zone,
  "canceled_at" timestamp WITH time zone,
  "trial_start" timestamp WITH time zone,
  "trial_end" timestamp WITH time zone,
  "organization_id" "uuid"
);
ALTER TABLE "public"."subscriptions" OWNER TO "postgres";
--
-- Name: organization_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."organization_members"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organization_members_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
--
-- Name: user_private_info; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE "public"."user_private_info" (
  "id" "uuid" NOT NULL,
  "created_at" timestamp WITH time zone DEFAULT "now"()
);
-- ALTER TABLE "public"."user_private_info" OWNER TO "supabase_admin";
--
-- Name: app_settings app_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."app_settings"
ADD CONSTRAINT "app_settings_pkey" PRIMARY KEY ("id");
--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."customers"
ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("stripe_customer_id", "organization_id");
--
-- Name: customers customers_stripe_customer_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."customers"
ADD CONSTRAINT "customers_stripe_customer_id_key" UNIQUE ("stripe_customer_id");
--
-- Name: prices price_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."prices"
ADD CONSTRAINT "price_pkey" PRIMARY KEY ("id");
--
-- Name: products product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."products"
ADD CONSTRAINT "product_pkey" PRIMARY KEY ("id");
--
-- Name: organizations_private_info projects_private_info_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."organizations_private_info"
ADD CONSTRAINT "projects_private_info_pkey" PRIMARY KEY ("id");
--
-- Name: subscriptions subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."subscriptions"
ADD CONSTRAINT "subscription_pkey" PRIMARY KEY ("id");
--
-- Name: organization_join_invitations organization_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."organization_join_invitations"
ADD CONSTRAINT "organization_invitations_pkey" PRIMARY KEY ("id");
--
-- Name: organization_members organization_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_members"
ADD CONSTRAINT "organization_members_pkey" PRIMARY KEY ("id");
--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organizations"
ADD CONSTRAINT "organizations_pkey" PRIMARY KEY ("id");
--
-- Name: user_private_info user_private_info_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."user_private_info"
ADD CONSTRAINT "user_private_info_pkey" PRIMARY KEY ("id");
--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."user_profiles"
ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("id");
--
-- Name: one_row_only_uidx; Type: INDEX; Schema: public; Owner: supabase_admin
--

CREATE UNIQUE INDEX "one_row_only_uidx" ON "public"."app_settings" USING "btree" ((TRUE));
--
-- Name: organizations on_organization_created; Type: TRIGGER; Schema: public; Owner: postgres
--

--
-- Name: customers customers_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."customers"
ADD CONSTRAINT "customers_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");
--
-- Name: organization_join_invitations organization_join_invitations_invitee_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."organization_join_invitations"
ADD CONSTRAINT "organization_join_invitations_invitee_user_id_fkey" FOREIGN KEY ("invitee_user_id") REFERENCES "public"."user_profiles"("id");
--
-- Name: organization_join_invitations organization_join_invitations_inviter_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."organization_join_invitations"
ADD CONSTRAINT "organization_join_invitations_inviter_user_id_fkey" FOREIGN KEY ("inviter_user_id") REFERENCES "public"."user_profiles"("id");
--
-- Name: organization_join_invitations organization_join_invitations_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."organization_join_invitations"
ADD CONSTRAINT "organization_join_invitations_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");
--
-- Name: organization_members organization_members_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_members"
ADD CONSTRAINT "organization_members_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "public"."user_profiles"("id");
--
-- Name: organization_members organization_members_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_members"
ADD CONSTRAINT "organization_members_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");
--
-- Name: organizations organizations_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organizations"
ADD CONSTRAINT "organizations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."user_profiles"("id");
--
-- Name: organizations_private_info organizations_private_info_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."organizations_private_info"
ADD CONSTRAINT "organizations_private_info_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."organizations"("id");
--
-- Name: prices prices_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."prices"
ADD CONSTRAINT "prices_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");
--
-- Name: subscriptions subscriptions_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."subscriptions"
ADD CONSTRAINT "subscriptions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");
--
-- Name: subscriptions subscriptions_price_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."subscriptions"
ADD CONSTRAINT "subscriptions_price_id_fkey" FOREIGN KEY ("price_id") REFERENCES "public"."prices"("id");
--
-- Name: user_private_info user_private_info_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY "public"."user_private_info"
ADD CONSTRAINT "user_private_info_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");
--
-- Name: user_profiles user_profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."user_profiles"
ADD CONSTRAINT "user_profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");
--
-- Name: products Active products are visible to everyone; Type: POLICY; Schema: public; Owner: postgres
--
