CREATE TABLE "public"."app_admins" (
  "user_id" text NOT NULL,
  "role" app_admin_role
);


ALTER TABLE "public"."app_admins" enable ROW LEVEL SECURITY;


CREATE TABLE "public"."organization_credits" (
  "organization_id" uuid NOT NULL,
  "credits" bigint NOT NULL DEFAULT '12'::bigint
);


ALTER TABLE "public"."organization_credits" enable ROW LEVEL SECURITY;


CREATE TABLE "public"."team_members" (
  "id" bigint generated by DEFAULT AS identity NOT NULL,
  "created_at" timestamp WITH time zone DEFAULT NOW(),
  "user_id" uuid NOT NULL REFERENCES "public"."user_profiles"("id") ON DELETE CASCADE,
  "role" project_team_member_role NOT NULL DEFAULT 'member'::project_team_member_role,
  "team_id" bigint NOT NULL
);

CREATE TABLE "public"."teams" (
  "id" bigint generated by DEFAULT AS identity NOT NULL,
  "created_at" timestamp WITH time zone DEFAULT NOW(),
  "organization_id" uuid NOT NULL,
  "name" text NOT NULL
);

ALTER TABLE "public"."teams" enable ROW LEVEL SECURITY;

CREATE TABLE "public"."projects" (
  "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
  "name" text NOT NULL,
  "created_at" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "organization_id" uuid NOT NULL,
  "team_id" bigint NOT NULL,
  "project_status" project_status NOT NULL DEFAULT 'draft'::project_status
);

ALTER TABLE "public"."projects" enable ROW LEVEL SECURITY;
